"""Inference Gateway Python SDK.

A modern Python SDK for the Inference Gateway API with full OpenAPI support
and type safety using Pydantic v2.
"""

from importlib.metadata import PackageNotFoundError, version

from inference_gateway.client import (
    InferenceGatewayAPIError,
    InferenceGatewayClient,
    InferenceGatewayError,
    InferenceGatewayValidationError,
)
from inference_gateway.models import (
    CacheControl,
    ChatCompletionMessageToolCall,
    ChatCompletionMessageToolCallChunk,
    ChatCompletionNamedToolChoice,
    ChatCompletionToolChoiceOption,
    CompletionUsage,
    ContentPart,
    ContextWindow,
    CreateChatCompletionRequest,
    CreateChatCompletionResponse,
    CreateChatCompletionStreamResponse,
    CreateImageRequest,
    CreateMessagesRequest,
    CreateResponseRequest,
    CreateSpeechRequest,
    FinishReason,
    FunctionObject,
    Google,
    Image,
    ImageContentPart,
    ImagesResponse,
    ImageURL,
    InputTokensDetails,
    ListModelsResponse,
    Message,
    MessageContent,
    MessageRole,
    MessagesDocumentBlock,
    MessagesDocumentSource,
    MessagesError,
    MessagesImageBlock,
    MessagesImageSource,
    MessagesMessage,
    MessagesMetadata,
    MessagesRedactedThinkingBlock,
    MessagesRequestContentBlock,
    MessagesResponse,
    MessagesResponseContentBlock,
    MessagesStreamEvent,
    MessagesTextBlock,
    MessagesThinkingBlock,
    MessagesTool,
    MessagesToolChoice,
    MessagesToolResultBlock,
    MessagesToolUseBlock,
    MessagesUsage,
    Modality,
    Model,
    ModelModalities,
    Pricing,
    Provider,
    Response,
    ResponseError,
    ResponseFormatJsonObject,
    ResponseFormatJsonSchema,
    ResponseFormatText,
    ResponseFunctionToolCall,
    ResponseInput,
    ResponseInputImage,
    ResponseInputItem,
    ResponseInputText,
    ResponseOutputItem,
    ResponseOutputMessage,
    ResponseOutputText,
    ResponseReasoning,
    ResponseReasoningItem,
    ResponseRole,
    ResponseStatus,
    ResponseStreamEvent,
    ResponseTextConfig,
    ResponseTool,
    ResponseToolChoice,
    ResponseUsage,
    SSEvent,
    TextContentPart,
    Thinking,
    ToolCallExtraContent,
    Usage,
)

try:
    __version__ = version("inference-gateway")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    # Client classes
    "InferenceGatewayClient",
    # Exceptions
    "InferenceGatewayError",
    "InferenceGatewayAPIError",
    "InferenceGatewayValidationError",
    # Core models
    "Provider",
    "Message",
    "MessageContent",
    "MessageRole",
    "ListModelsResponse",
    "Modality",
    "ModelModalities",
    "CreateChatCompletionRequest",
    "CreateChatCompletionResponse",
    "CreateChatCompletionStreamResponse",
    "SSEvent",
    "Model",
    "CompletionUsage",
    "ChatCompletionMessageToolCall",
    "ChatCompletionMessageToolCallChunk",
    "FunctionObject",
    "FinishReason",
    "ToolCallExtraContent",
    "Google",
    # Tool choice
    "ChatCompletionToolChoiceOption",
    "ChatCompletionNamedToolChoice",
    # Structured outputs / response format
    "ResponseFormatText",
    "ResponseFormatJsonObject",
    "ResponseFormatJsonSchema",
    # Multimodal content
    "ContentPart",
    "TextContentPart",
    "ImageContentPart",
    "ImageURL",
    # Images API
    "CreateImageRequest",
    "ImagesResponse",
    "Image",
    "Usage",
    "InputTokensDetails",
    # Audio API
    "CreateSpeechRequest",
    # Responses API
    "CreateResponseRequest",
    "Response",
    "ResponseStreamEvent",
    "ResponseInput",
    "ResponseInputItem",
    "ResponseInputText",
    "ResponseInputImage",
    "ResponseTool",
    "ResponseToolChoice",
    "ResponseReasoning",
    "ResponseTextConfig",
    "ResponseStatus",
    "ResponseError",
    "ResponseOutputItem",
    "ResponseOutputMessage",
    "ResponseOutputText",
    "ResponseFunctionToolCall",
    "ResponseReasoningItem",
    "ResponseUsage",
    "ResponseRole",
    # Messages API (Anthropic-compatible)
    "CreateMessagesRequest",
    "MessagesResponse",
    "MessagesStreamEvent",
    "MessagesMessage",
    "MessagesTool",
    "MessagesToolChoice",
    "MessagesMetadata",
    "MessagesUsage",
    "MessagesError",
    "MessagesRequestContentBlock",
    "MessagesResponseContentBlock",
    "MessagesTextBlock",
    "MessagesImageBlock",
    "MessagesImageSource",
    "MessagesDocumentBlock",
    "MessagesDocumentSource",
    "MessagesToolUseBlock",
    "MessagesToolResultBlock",
    "MessagesThinkingBlock",
    "MessagesRedactedThinkingBlock",
    "CacheControl",
    "Thinking",
]
