# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-05T15:40:46+00:00

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Provider(
    RootModel[
        Literal[
            "ollama",
            "ollama_cloud",
            "groq",
            "llamacpp",
            "openai",
            "cloudflare",
            "cohere",
            "anthropic",
            "deepseek",
            "google",
            "mistral",
            "minimax",
            "moonshot",
            "nvidia",
        ]
    ]
):
    root: Literal[
        "ollama",
        "ollama_cloud",
        "groq",
        "llamacpp",
        "openai",
        "cloudflare",
        "cohere",
        "anthropic",
        "deepseek",
        "google",
        "mistral",
        "minimax",
        "moonshot",
        "nvidia",
    ]


class ProviderSpecificResponse(BaseModel):
    """
    Provider-specific response format. Examples:

    OpenAI GET /v1/models?provider=openai response:
    ```json
    {
      "provider": "openai",
      "object": "list",
      "data": [
        {
          "id": "gpt-4",
          "object": "model",
          "created": 1687882410,
          "owned_by": "openai",
          "served_by": "openai"
        }
      ]
    }
    ```

    Anthropic GET /v1/models?provider=anthropic response:
    ```json
    {
      "provider": "anthropic",
      "object": "list",
      "data": [
        {
          "id": "gpt-4",
          "object": "model",
          "created": 1687882410,
          "owned_by": "openai",
          "served_by": "openai"
        }
      ]
    }
    ```

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )


class ProviderAuthType(RootModel[Literal["bearer", "xheader", "query", "none"]]):
    root: Literal["bearer", "xheader", "query", "none"]
    """
    Authentication type for providers
    """


class SSEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: (
        Literal[
            "message-start",
            "stream-start",
            "content-start",
            "content-delta",
            "content-end",
            "message-end",
            "stream-end",
        ]
        | None
    ) = None
    data: str | None = None
    retry: int | None = None


class Endpoints(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    models: str
    chat: str


class Error(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: str | None = None


class MessageRole(RootModel[Literal["system", "user", "assistant", "tool"]]):
    root: Literal["system", "user", "assistant", "tool"]
    """
    Role of the message sender
    """


class TextContentPart(BaseModel):
    """
    Text content part
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["text"] = "text"
    """
    Content type identifier
    """
    text: str
    """
    The text content
    """


class ImageURL(BaseModel):
    """
    Image URL configuration
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    url: str
    """
    URL of the image (data URLs supported)
    """
    detail: Literal["auto", "low", "high"] = "auto"
    """
    Image detail level for vision processing
    """


class Model(BaseModel):
    """
    Common model information
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    object: str
    created: int
    owned_by: str
    served_by: Provider


class ListModelsResponse(BaseModel):
    """
    Response structure for listing models
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: Provider | None = None
    object: str
    data: Annotated[Sequence[Model], Field(validate_default=True)] = []


class MCPTool(BaseModel):
    """
    An MCP tool definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(examples=["read_file"])]
    """
    The name of the tool
    """
    description: Annotated[str, Field(examples=["Read content from a file"])]
    """
    A description of what the tool does
    """
    server: Annotated[str, Field(examples=["http://mcp-filesystem-server:8083/mcp"])]
    """
    The MCP server that provides this tool
    """
    input_schema: Annotated[
        Mapping[str, Any] | None,
        Field(
            examples=[
                {
                    "type": "object",
                    "properties": {
                        "file_path": {"type": "string", "description": "Path to the file to read"}
                    },
                    "required": ["file_path"],
                }
            ]
        ),
    ] = None
    """
    JSON schema for the tool's input parameters
    """


class FunctionParameters(BaseModel):
    """
    The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.
    Omitting `parameters` defines a function with an empty parameter list.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )


class ChatCompletionToolType(RootModel[Literal["function"]]):
    root: Literal["function"] = "function"
    """
    The type of the tool. Currently, only `function` is supported.
    """


class CompletionUsage(BaseModel):
    """
    Usage statistics for the completion request.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    completion_tokens: int = 0
    """
    Number of tokens in the generated completion.
    """
    prompt_tokens: int = 0
    """
    Number of tokens in the prompt.
    """
    total_tokens: int = 0
    """
    Total number of tokens used in the request (prompt + completion).
    """


class ChatCompletionStreamOptions(BaseModel):
    """
    Options for streaming response. Only set this when you set `stream: true`.

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    include_usage: bool
    """
    If set, an additional chunk will be streamed before the `data: [DONE]` message. The `usage` field on this chunk shows the token usage statistics for the entire request, and the `choices` field will always be an empty array. All other chunks will also include a `usage` field, but with a null value.

    """


class Stop(RootModel[Sequence[str]]):
    root: Annotated[Sequence[str], Field(max_length=4, min_length=1)]
    """
    Up to 4 sequences where the API will stop generating further tokens.

    """


class ResponseFormatText(BaseModel):
    """
    Default response format. Used to generate text responses.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["text"] = "text"
    """
    The type of response format being defined. Always `text`.
    """


class ResponseFormatJsonObject(BaseModel):
    """
    JSON object response format. An older method of generating JSON responses. Using `json_schema` is recommended for models that support it. Note that the model will not generate JSON without a system or user message instructing it to do so.

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["json_object"] = "json_object"
    """
    The type of response format being defined. Always `json_object`.
    """


class ResponseFormatJsonSchemaSchema(BaseModel):
    """
    The schema for the response format, described as a JSON Schema object.

    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )


class Function(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    The name of the function to call.
    """


class ChatCompletionNamedToolChoice(BaseModel):
    """
    Specifies a tool the model should use. Use to force the model to call a specific function.

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: ChatCompletionToolType
    function: Function


class ChatCompletionMessageToolCallFunction(BaseModel):
    """
    The function that the model called.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    The name of the function to call.
    """
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    """


class Google(BaseModel):
    """
    Google Gemini-specific extra content.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    thought_signature: str | None = None
    """
    Opaque signature returned with reasoning-enabled tool calls.
    Must be echoed back verbatim in the next request that includes
    this tool call, or Google will reject the request.

    """


class ToolCallExtraContent(BaseModel):
    """
    Provider-specific opaque data attached to a tool call. The contents are
    not interpreted by the gateway, but must be echoed back verbatim on the
    next request that references this tool call. Currently used by Google
    Gemini extended-thinking models to carry the per-call `thought_signature`.
    Other providers may ignore the field.

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    google: Google | None = None
    """
    Google Gemini-specific extra content.
    """


class TopLogprob(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    """
    The token.
    """
    logprob: float
    """
    The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
    """
    bytes: Sequence[int]
    """
    A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
    """


class ChatCompletionTokenLogprob(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    """
    The token.
    """
    logprob: float
    """
    The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
    """
    bytes: Sequence[int]
    """
    A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
    """
    top_logprobs: Sequence[TopLogprob]
    """
    List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.
    """


class FinishReason(
    RootModel[Literal["stop", "length", "tool_calls", "content_filter", "function_call"]]
):
    root: Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
    """
    The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
    `length` if the maximum number of tokens specified in the request was reached,
    `content_filter` if content was omitted due to a flag from our content filters,
    `tool_calls` if the model called a tool.

    """


class Config(RootModel[Any]):
    root: Any


class ImageContentPart(BaseModel):
    """
    Image content part
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["image_url"] = "image_url"
    """
    Content type identifier
    """
    image_url: ImageURL


class ListToolsResponse(BaseModel):
    """
    Response structure for listing MCP tools
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    object: Annotated[str, Field(examples=["list"])]
    """
    Always "list"
    """
    data: Annotated[Sequence[MCPTool], Field(validate_default=True)] = []
    """
    Array of available MCP tools
    """


class FunctionObject(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    A description of what the function does, used by the model to choose when and how to call the function.
    """
    name: str
    """
    The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    """
    parameters: FunctionParameters | None = None
    strict: bool = False
    """
    Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Learn more about Structured Outputs in the [function calling guide](docs/guides/function-calling).
    """


class ChatCompletionTool(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: ChatCompletionToolType
    function: FunctionObject


class JsonSchema(BaseModel):
    """
    Structured Outputs configuration options, including a JSON Schema.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    A description of what the response format is for, used by the model to determine how to respond in the format.

    """
    name: str
    """
    The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.

    """
    schema_: Annotated[ResponseFormatJsonSchemaSchema | None, Field(alias="schema")] = None
    strict: bool = False
    """
    Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`.

    """


class ResponseFormatJsonSchema(BaseModel):
    """
    JSON Schema response format. Used to generate structured JSON responses.

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal["json_schema"] = "json_schema"
    """
    The type of response format being defined. Always `json_schema`.
    """
    json_schema: JsonSchema
    """
    Structured Outputs configuration options, including a JSON Schema.
    """


class ChatCompletionToolChoiceOption(
    RootModel[Literal["none", "auto", "required"] | ChatCompletionNamedToolChoice]
):
    root: Literal["none", "auto", "required"] | ChatCompletionNamedToolChoice
    """
    Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. Specifying a particular tool via `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool.
    `none` is the default when no tools are present. `auto` is the default if tools are present.

    """


class ChatCompletionMessageToolCall(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    The ID of the tool call.
    """
    type: ChatCompletionToolType
    function: ChatCompletionMessageToolCallFunction
    extra_content: ToolCallExtraContent | None = None


class Logprobs(BaseModel):
    """
    Log probability information for the choice.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    content: Sequence[ChatCompletionTokenLogprob]
    """
    A list of message content tokens with log probability information.
    """
    refusal: Sequence[ChatCompletionTokenLogprob]
    """
    A list of message refusal tokens with log probability information.
    """


class ChatCompletionMessageToolCallChunk(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: int
    id: str | None = None
    """
    The ID of the tool call.
    """
    type: str | None = None
    """
    The type of the tool. Currently, only `function` is supported.
    """
    function: ChatCompletionMessageToolCallFunction | None = None
    extra_content: ToolCallExtraContent | None = None


class ContentPart(RootModel[TextContentPart | ImageContentPart]):
    root: TextContentPart | ImageContentPart
    """
    A content part within a multimodal message
    """


class ChatCompletionStreamResponseDelta(BaseModel):
    """
    A chat completion delta generated by streamed model responses.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    content: str
    """
    The contents of the chunk message.
    """
    reasoning_content: str | None = None
    """
    The reasoning content of the chunk message.
    """
    reasoning: str | None = None
    """
    The reasoning of the chunk message. Same as reasoning_content.
    """
    tool_calls: Sequence[ChatCompletionMessageToolCallChunk] | None = None
    role: MessageRole
    refusal: str | None = None
    """
    The refusal message generated by the model.
    """


class MessageContent(RootModel[str | Sequence[ContentPart]]):
    root: str | Sequence[ContentPart]
    """
    Message content - either text or multimodal content parts
    """


class ChatCompletionStreamChoice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    delta: ChatCompletionStreamResponseDelta
    logprobs: Logprobs | None = None
    """
    Log probability information for the choice.
    """
    finish_reason: FinishReason
    index: int
    """
    The index of the choice in the list of choices.
    """


class CreateChatCompletionStreamResponse(BaseModel):
    """
    Represents a streamed chunk of a chat completion response returned
    by the model, based on the provided input.

    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    A unique identifier for the chat completion. Each chunk has the same ID.
    """
    choices: Sequence[ChatCompletionStreamChoice]
    """
    A list of chat completion choices. Can contain more than one elements if `n` is greater than 1. Can also be empty for the
    last chunk if you set `stream_options: {"include_usage": true}`.

    """
    created: int
    """
    The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
    """
    model: str
    """
    The model to generate the completion.
    """
    system_fingerprint: str | None = None
    """
    This fingerprint represents the backend configuration that the model runs with.
    Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.

    """
    object: str
    """
    The object type, which is always `chat.completion.chunk`.
    """
    usage: CompletionUsage | None = None
    reasoning_format: str | None = None
    """
    The format of the reasoning content. Can be `raw` or `parsed`.
    When specified as raw some reasoning models will output <think /> tags. When specified as parsed the model will output the reasoning under reasoning_content.

    """


class Message(BaseModel):
    """
    Message structure for provider requests
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: MessageRole
    content: MessageContent
    tool_calls: Sequence[ChatCompletionMessageToolCall] | None = None
    tool_call_id: str | None = None
    reasoning_content: str | None = None
    """
    The reasoning content of the chunk message.
    """
    reasoning: str | None = None
    """
    The reasoning of the chunk message. Same as reasoning_content.
    """


class CreateChatCompletionRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    model: str
    """
    Model ID to use
    """
    messages: Annotated[Sequence[Message], Field(min_length=1)]
    """
    A list of messages comprising the conversation so far.

    """
    max_tokens: Annotated[int | None, Field(deprecated=True)] = None
    """
    The maximum number of tokens that can be generated in the chat completion. This value can be used to control costs for text generated via API. This value is now deprecated in favor of `max_completion_tokens`, and is not compatible with o-series models.

    """
    max_completion_tokens: int | None = None
    """
    An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens.

    """
    temperature: Annotated[float, Field(ge=0.0, le=2.0)] = 1
    """
    What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

    """
    top_p: Annotated[float, Field(ge=0.0, le=1.0)] = 1
    """
    An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass.

    """
    frequency_penalty: Annotated[float, Field(ge=-2.0, le=2.0)] = 0
    """
    Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.

    """
    presence_penalty: Annotated[float, Field(ge=-2.0, le=2.0)] = 0
    """
    Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.

    """
    n: Annotated[int, Field(ge=1, le=128)] = 1
    """
    How many chat completion choices to generate for each input message.

    """
    stop: str | Stop | None = None
    """
    Up to 4 sequences where the API will stop generating further tokens.

    """
    seed: int | None = None
    """
    If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result. Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.

    """
    logprobs: bool = False
    """
    Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`.

    """
    top_logprobs: Annotated[int | None, Field(ge=0, le=20)] = None
    """
    An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.

    """
    response_format: (
        ResponseFormatText | ResponseFormatJsonSchema | ResponseFormatJsonObject | None
    ) = None
    """
    An object specifying the format that the model must output. Setting to `{ "type": "json_schema", "json_schema": {...} }` enables Structured Outputs which guarantees the model will match your supplied JSON schema. Setting to `{ "type": "json_object" }` enables the older JSON mode, which ensures the message the model generates is valid JSON.

    """
    logit_bias: Mapping[str, int] | None = None
    """
    Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. The bias is added to the logits generated by the model prior to sampling.

    """
    user: str | None = None
    """
    A unique identifier representing your end-user, which can help to monitor and detect abuse.

    """
    stream: bool = False
    """
    If set to true, the model response data will be streamed to the client as it is generated using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).

    """
    stream_options: ChatCompletionStreamOptions | None = None
    tools: Sequence[ChatCompletionTool] | None = None
    """
    A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.

    """
    tool_choice: ChatCompletionToolChoiceOption | None = None
    parallel_tool_calls: bool = True
    """
    Whether to enable parallel function calling during tool use.

    """
    reasoning_format: str | None = None
    """
    The format of the reasoning content. Can be `raw` or `parsed`.
    When specified as raw some reasoning models will output <think /> tags. When specified as parsed the model will output the reasoning under `reasoning` or `reasoning_content` attribute.

    """
    reasoning_effort: Literal["minimal", "low", "medium", "high"] | None = None
    """
    Constrains effort on reasoning for reasoning models. Currently supported values are `minimal`, `low`, `medium`, and `high`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.

    """


class ChatCompletionChoice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    finish_reason: FinishReason
    index: int
    """
    The index of the choice in the list of choices.
    """
    message: Message
    logprobs: Logprobs | None = None
    """
    Log probability information for the choice.
    """


class CreateChatCompletionResponse(BaseModel):
    """
    Represents a chat completion response returned by model, based on the provided input.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    A unique identifier for the chat completion.
    """
    choices: Sequence[ChatCompletionChoice]
    """
    A list of chat completion choices. Can be more than one if `n` is greater than 1.
    """
    created: int
    """
    The Unix timestamp (in seconds) of when the chat completion was created.
    """
    model: str
    """
    The model used for the chat completion.
    """
    object: str
    """
    The object type, which is always `chat.completion`.
    """
    usage: CompletionUsage | None = None
